// server/api/movies.ts
// Tổng 100 phim: 20 phim × 5 category = 100 phim
// Mỗi category có pagination: 5 phim/page × 4 page = 20 phim/category
export default defineEventHandler(() => {
  return [
    // ===== DANH MỤC 1: PHIM MỚI CẬP NHẬT (20 PHIM) =====
    { id: 1, title: "Lật Mặt 7: Một Điều Ước", poster: "/images/posters/lat-mat-7.jpg", year: "2024", genre: "Tâm Lý, Gia Đình", rating: 9.0 },
    { id: 2, title: "Mai", poster: "/images/posters/mai.jpg", year: "2024", genre: "Tâm Lý, Kịch", rating: 8.5 },
    { id: 3, title: "Deadpool & Wolverine", poster: "/images/posters/deadpool-wolverine.jpg", year: "2024", genre: "Hành Động, Hài", rating: 8.8 },
    { id: 4, title: "Dune: Part Two", poster: "/images/posters/dune-part-two.jpg", year: "2024", genre: "Viễn Tưởng, Phiêu Lưu", rating: 9.2 },
    { id: 5, title: "Inside Out 2", poster: "/images/posters/inside-out-2.jpg", year: "2024", genre: "Hoạt Hình, Gia Đình", rating: 8.9 },
    { id: 6, title: "The Brutalist", poster: "/images/posters/the-brutalist.jpg", year: "2023", genre: "Chính Kịch", rating: 8.7 },
    { id: 7, title: "Oppenheimer", poster: "/images/posters/oppenheimer.jpg", year: "2023", genre: "Chính Kịch, Lịch Sử", rating: 8.6 },
    { id: 8, title: "Barbie", poster: "/images/posters/barbie.jpg", year: "2023", genre: "Hài, Phiêu Lưu", rating: 8.0 },
    { id: 9, title: "Killers of the Flower Moon", poster: "/images/posters/killers.jpg", year: "2023", genre: "Tội Phạm, Chính Kịch", rating: 8.8 },
    { id: 10, title: "The Godfather", poster: "/images/posters/godfather.jpg", year: "1972", genre: "Tội Phạm, Chính Kịch", rating: 9.3 },
    { id: 11, title: "Avatar", poster: "/images/posters/avatar.jpg", year: "2009", genre: "Viễn Tưởng, Phiêu Lưu", rating: 7.9 },
    { id: 12, title: "Titanic", poster: "/images/posters/titanic.jpg", year: "1997", genre: "Tâm Lý, Thảm Họa", rating: 7.8 },
    { id: 13, title: "The Shawshank Redemption", poster: "/images/posters/shawshank.jpg", year: "1994", genre: "Chính Kịch", rating: 9.3 },
    { id: 14, title: "Inception", poster: "/images/posters/inception.jpg", year: "2010", genre: "Viễn Tưởng, Hành Động", rating: 8.8 },
    { id: 15, title: "The Dark Knight", poster: "/images/posters/dark-knight.jpg", year: "2008", genre: "Hành Động, Tội Phạm", rating: 9.0 },
    { id: 16, title: "Interstellar", poster: "/images/posters/interstellar.jpg", year: "2014", genre: "Viễn Tưởng, Kịch", rating: 8.6 },
    { id: 17, title: "Pulp Fiction", poster: "/images/posters/pulp-fiction.jpg", year: "1994", genre: "Tội Phạm, Chính Kịch", rating: 8.9 },
    { id: 18, title: "Forrest Gump", poster: "/images/posters/forrest-gump.jpg", year: "1994", genre: "Chính Kịch, Tâm Lý", rating: 8.8 },
    { id: 19, title: "The Matrix", poster: "/images/posters/matrix.jpg", year: "1999", genre: "Viễn Tưởng, Hành Động", rating: 8.7 },
    { id: 20, title: "Gladiator", poster: "/images/posters/gladiator.jpg", year: "2000", genre: "Hành Động, Lịch Sử", rating: 8.5 },

    // ===== DANH MỤC 2: PHIM HOT HIỆN TẠI (20 PHIM) =====
    { id: 21, title: "The Lion King", poster: "/images/posters/lion-king.jpg", year: "1994", genre: "Hoạt Hình, Gia Đình", rating: 8.5 },
    { id: 22, title: "Jaws", poster: "/images/posters/jaws.jpg", year: "1975", genre: "Kinh Dị, Thảm Họa", rating: 8.1 },
    { id: 23, title: "E.T. the Extra-Terrestrial", poster: "/images/posters/et.jpg", year: "1982", genre: "Viễn Tưởng, Gia Đình", rating: 7.9 },
    { id: 24, title: "Back to the Future", poster: "/images/posters/bttf.jpg", year: "1985", genre: "Viễn Tưởng, Hài", rating: 8.5 },
    { id: 25, title: "The Sixth Sense", poster: "/images/posters/sixth-sense.jpg", year: "1999", genre: "Kinh Dị, Kịch", rating: 8.2 },
    { id: 26, title: "Jurassic Park", poster: "/images/posters/jurassic-park.jpg", year: "1993", genre: "Viễn Tưởng, Hành Động", rating: 8.1 },
    { id: 27, title: "Independence Day", poster: "/images/posters/independence-day.jpg", year: "1996", genre: "Viễn Tưởng, Hành Động", rating: 7.0 },
    { id: 28, title: "The Avengers", poster: "/images/posters/avengers.jpg", year: "2012", genre: "Hành Động, Viễn Tưởng", rating: 8.0 },
    { id: 29, title: "Iron Man", poster: "/images/posters/iron-man.jpg", year: "2008", genre: "Hành Động, Viễn Tưởng", rating: 7.9 },
    { id: 30, title: "Thor", poster: "/images/posters/thor.jpg", year: "2011", genre: "Hành Động, Viễn Tưởng", rating: 7.0 },
    { id: 31, title: "Captain America", poster: "/images/posters/captain-america.jpg", year: "2011", genre: "Hành Động, Viễn Tưởng", rating: 6.9 },
    { id: 32, title: "Black Panther", poster: "/images/posters/black-panther.jpg", year: "2018", genre: "Hành Động, Viễn Tưởng", rating: 7.3 },
    { id: 33, title: "Doctor Strange", poster: "/images/posters/doctor-strange.jpg", year: "2016", genre: "Hành Động, Viễn Tưởng", rating: 7.5 },
    { id: 34, title: "Guardians of the Galaxy", poster: "/images/posters/guardians.jpg", year: "2014", genre: "Hành Động, Hài", rating: 8.0 },
    { id: 35, title: "Ant-Man", poster: "/images/posters/ant-man.jpg", year: "2015", genre: "Hành Động, Hài", rating: 7.3 },
    { id: 36, title: "Spider-Man", poster: "/images/posters/spider-man.jpg", year: "2002", genre: "Hành Động, Viễn Tưởng", rating: 7.3 },
    { id: 37, title: "X-Men", poster: "/images/posters/x-men.jpg", year: "2000", genre: "Hành Động, Viễn Tưởng", rating: 7.4 },
    { id: 38, title: "Fantastic Four", poster: "/images/posters/fantastic-four.jpg", year: "2005", genre: "Hành Động, Viễn Tưởng", rating: 5.7 },
    { id: 39, title: "Blade", poster: "/images/posters/blade.jpg", year: "1998", genre: "Hành Động, Kinh Dị", rating: 7.1 },
    { id: 40, title: "The Hulk", poster: "/images/posters/hulk.jpg", year: "2003", genre: "Hành Động, Viễn Tưởng", rating: 5.7 },

    // ===== DANH MỤC 3: PHIM ĐƯỢC XEM NHIỀU (20 PHIM) =====
    { id: 41, title: "Avatar 2: The Way of Water", poster: "/images/posters/avatar-2.jpg", year: "2022", genre: "Viễn Tưởng, Phiêu Lưu", rating: 7.2 },
    { id: 42, title: "Top Gun: Maverick", poster: "/images/posters/top-gun-maverick.jpg", year: "2022", genre: "Hành Động, Chính Kịch", rating: 8.3 },
    { id: 43, title: "Doctor Strange 2", poster: "/images/posters/ds2.jpg", year: "2022", genre: "Hành Động, Viễn Tưởng", rating: 6.9 },
    { id: 44, title: "Lightyear", poster: "/images/posters/lightyear.jpg", year: "2022", genre: "Hoạt Hình, Viễn Tưởng", rating: 7.0 },
    { id: 45, title: "Minions: Rise of Gru", poster: "/images/posters/minions.jpg", year: "2022", genre: "Hoạt Hình, Hài", rating: 6.6 },
    { id: 46, title: "The Lost City", poster: "/images/posters/lost-city.jpg", year: "2022", genre: "Phiêu Lưu, Hài", rating: 6.5 },
    { id: 47, title: "Uncharted", poster: "/images/posters/uncharted.jpg", year: "2022", genre: "Hành Động, Phiêu Lưu", rating: 6.3 },
    { id: 48, title: "Morbius", poster: "/images/posters/morbius.jpg", year: "2022", genre: "Hành Động, Kinh Dị", rating: 5.2 },
    { id: 49, title: "The Batman", poster: "/images/posters/the-batman.jpg", year: "2022", genre: "Hành Động, Tội Phạm", rating: 7.7 },
    { id: 50, title: "Everything Everywhere All at Once", poster: "/images/posters/everything.jpg", year: "2022", genre: "Viễn Tưởng, Chính Kịch", rating: 8.0 },
    { id: 51, title: "Nope", poster: "/images/posters/nope.jpg", year: "2022", genre: "Khoa Học, Kinh Dị", rating: 6.8 },
    { id: 52, title: "The Woman King", poster: "/images/posters/woman-king.jpg", year: "2022", genre: "Hành Động, Chính Kịch", rating: 6.5 },
    { id: 53, title: "Blonde", poster: "/images/posters/blonde.jpg", year: "2022", genre: "Chính Kịch, Tiểu Sử", rating: 5.3 },
    { id: 54, title: "Hustle", poster: "/images/posters/hustle.jpg", year: "2022", genre: "Thể Thao, Chính Kịch", rating: 7.5 },
    { id: 55, title: "The Gray Man", poster: "/images/posters/gray-man.jpg", year: "2022", genre: "Hành Động, Hình Sự", rating: 6.5 },
    { id: 56, title: "Glass Onion", poster: "/images/posters/glass-onion.jpg", year: "2022", genre: "Hình Sự, Hài", rating: 7.3 },
    { id: 57, title: "See How They Run", poster: "/images/posters/see-how-they-run.jpg", year: "2022", genre: "Hình Sự, Hài", rating: 6.9 },
    { id: 58, title: "Aftersun", poster: "/images/posters/aftersun.jpg", year: "2022", genre: "Chính Kịch", rating: 7.2 },
    { id: 59, title: "TÁR", poster: "/images/posters/tar.jpg", year: "2022", genre: "Chính Kịch", rating: 7.8 },
    { id: 60, title: "The Eternal Memory", poster: "/images/posters/eternal-memory.jpg", year: "2022", genre: "Chính Kịch, Tiểu Sử", rating: 7.9 },

    // ===== DANH MỤC 4: PHIM TOP TRENDING (20 PHIM) =====
    { id: 61, title: "Barbie 2024", poster: "/images/posters/barbie-2024.jpg", year: "2024", genre: "Hài, Phiêu Lưu", rating: 8.2 },
    { id: 62, title: "Oppenheimer 2024", poster: "/images/posters/oppenheimer-2024.jpg", year: "2024", genre: "Chính Kịch, Lịch Sử", rating: 8.7 },
    { id: 63, title: "Killers of the Flower Moon 2024", poster: "/images/posters/killers-2024.jpg", year: "2024", genre: "Tội Phạm, Chính Kịch", rating: 8.5 },
    { id: 64, title: "The Brutalist 2024", poster: "/images/posters/brutalist-2024.jpg", year: "2024", genre: "Chính Kịch", rating: 8.4 },
    { id: 65, title: "American Fiction", poster: "/images/posters/american-fiction.jpg", year: "2023", genre: "Chính Kịch, Hài", rating: 8.0 },
    { id: 66, title: "Past Lives", poster: "/images/posters/past-lives.jpg", year: "2023", genre: "Tâm Lý, Chính Kịch", rating: 8.0 },
    { id: 67, title: "The Iron Claw", poster: "/images/posters/iron-claw.jpg", year: "2023", genre: "Chính Kịch, Tiểu Sử", rating: 7.9 },
    { id: 68, title: "Anatomy of a Fall", poster: "/images/posters/anatomy-of-fall.jpg", year: "2023", genre: "Tội Phạm, Chính Kịch", rating: 8.0 },
    { id: 69, title: "The Zone of Interest", poster: "/images/posters/zone-of-interest.jpg", year: "2023", genre: "Chính Kịch, Lịch Sử", rating: 7.6 },
    { id: 70, title: "Priscilla", poster: "/images/posters/priscilla.jpg", year: "2023", genre: "Chính Kịch, Tiểu Sử", rating: 6.8 },
    { id: 71, title: "Passages", poster: "/images/posters/passages.jpg", year: "2023", genre: "Chính Kịch, Tâm Lý", rating: 6.9 },
    { id: 72, title: "May December", poster: "/images/posters/may-december.jpg", year: "2023", genre: "Chính Kịch", rating: 6.6 },
    { id: 73, title: "The Iron Claw", poster: "/images/posters/iron-claw-2.jpg", year: "2023", genre: "Chính Kịch, Tiểu Sử", rating: 7.8 },
    { id: 74, title: "Didi", poster: "/images/posters/didi.jpg", year: "2023", genre: "Chính Kịch", rating: 6.7 },
    { id: 75, title: "Go Big or Go Home", poster: "/images/posters/go-big.jpg", year: "2023", genre: "Chính Kịch", rating: 6.5 },
    { id: 76, title: "The Eternal Memory", poster: "/images/posters/eternal-memory-2.jpg", year: "2023", genre: "Chính Kịch", rating: 7.7 },
    { id: 77, title: "Talk To Me", poster: "/images/posters/talk-to-me.jpg", year: "2022", genre: "Kinh Dị", rating: 7.0 },
    { id: 78, title: "Living", poster: "/images/posters/living.jpg", year: "2022", genre: "Chính Kịch, Tâm Lý", rating: 7.5 },
    { id: 79, title: "Close", poster: "/images/posters/close.jpg", year: "2022", genre: "Chính Kịch", rating: 7.2 },
    { id: 80, title: "The Quiet Girl", poster: "/images/posters/quiet-girl.jpg", year: "2022", genre: "Chính Kịch", rating: 7.6 },

    // ===== DANH MỤC 5: PHIM HÔM NAY (20 PHIM) =====
    { id: 81, title: "Dune", poster: "/images/posters/dune.jpg", year: "2021", genre: "Viễn Tưởng, Phiêu Lưu", rating: 8.0 },
    { id: 82, title: "No Time to Die", poster: "/images/posters/no-time-to-die.jpg", year: "2021", genre: "Hành Động, Gián Điệp", rating: 7.3 },
    { id: 83, title: "Spider-Man: No Way Home", poster: "/images/posters/spider-man-nwh.jpg", year: "2021", genre: "Hành Động, Viễn Tưởng", rating: 7.4 },
    { id: 84, title: "Eternals", poster: "/images/posters/eternals.jpg", year: "2021", genre: "Hành Động, Viễn Tưởng", rating: 5.9 },
    { id: 85, title: "Shang-Chi", poster: "/images/posters/shang-chi.jpg", year: "2021", genre: "Hành Động, Viễn Tưởng", rating: 7.4 },
    { id: 86, title: "Black Widow", poster: "/images/posters/black-widow.jpg", year: "2021", genre: "Hành Động, Viễn Tưởng", rating: 6.3 },
    { id: 87, title: "Loki", poster: "/images/posters/loki.jpg", year: "2021", genre: "Hành Động, Viễn Tưởng", rating: 8.2 },
    { id: 88, title: "Hawkeye", poster: "/images/posters/hawkeye.jpg", year: "2021", genre: "Hành Động, Viễn Tưởng", rating: 7.3 },
    { id: 89, title: "The Suicide Squad", poster: "/images/posters/suicide-squad.jpg", year: "2021", genre: "Hành Động, Hài", rating: 7.2 },
    { id: 90, title: "Black Widow: Prequel", poster: "/images/posters/bw-prequel.jpg", year: "2021", genre: "Hành Động, Chính Kịch", rating: 7.0 },
    { id: 91, title: "Godzilla vs. Kong", poster: "/images/posters/gvk.jpg", year: "2021", genre: "Hành Động, Kinh Dị", rating: 6.2 },
    { id: 92, title: "The Tomorrow War", poster: "/images/posters/tomorrow-war.jpg", year: "2021", genre: "Viễn Tưởng, Hành Động", rating: 6.5 },
    { id: 93, title: "Jungle Cruise", poster: "/images/posters/jungle-cruise.jpg", year: "2021", genre: "Phiêu Lưu, Hài", rating: 6.5 },
    { id: 94, title: "Free Guy", poster: "/images/posters/free-guy.jpg", year: "2021", genre: "Hành Động, Hài", rating: 6.7 },
    { id: 95, title: "Candyman", poster: "/images/posters/candyman.jpg", year: "2021", genre: "Kinh Dị, Chính Kịch", rating: 6.9 },
    { id: 96, title: "Old", poster: "/images/posters/old.jpg", year: "2021", genre: "Kinh Dị, Bí Ẩn", rating: 5.8 },
    { id: 97, title: "The Suicide Squad: Bloodsport", poster: "/images/posters/bloodsport.jpg", year: "2021", genre: "Hành Động, Hài", rating: 7.1 },
    { id: 98, title: "Snake Eyes", poster: "/images/posters/snake-eyes.jpg", year: "2021", genre: "Hành Động, Phiêu Lưu", rating: 5.6 },
    { id: 99, title: "Resident Evil: Welcome to Raccoon City", poster: "/images/posters/resident-evil.jpg", year: "2021", genre: "Kinh Dị, Hành Động", rating: 5.3 },
    { id: 100, title: "Venom: Let There Be Carnage", poster: "/images/posters/venom-2.jpg", year: "2021", genre: "Hành Động, Viễn Tưởng", rating: 5.7 }
  ]
})